CREATE TABLE IF NOT EXISTS apps(
    id UUID PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE,
    name VARCHAR(255) NOT NULL,
    approved BOOLEAN,
    published BOOLEAN NOT NULL,
    kind VARCHAR(255) NOT NULL, -- ENUM in the code/model declaration
    price_tier INT
);

CREATE TABLE IF NOT EXISTS users(
    id UUID PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL CONSTRAINT uk_users_email UNIQUE
);

CREATE TABLE IF NOT EXISTS transactions(
    id UUID PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE,
    user_id UUID CONSTRAINT fk_transactions_user REFERENCES users(id) ON UPDATE CASCADE ON DELETE SET NULL,
    app_id UUID CONSTRAINT fk_transactions_app REFERENCES apps(id) ON UPDATE CASCADE ON DELETE SET NULL
);